[package]
name = "hexspace"
version = "0.1.0"
authors = ["Roman S. Borschel <roman@pkaboo.org>"]
edition = "2018"

[dependencies]
hexworld = { path = "../core" }
hexworld-ggez = { path = "../ggez" }
ggez = { git = "https://github.com/ggez/ggez" }

