stages:
  - test
  - deploy

before_script:
  - apt -qq update
  - apt -qq -y install libasound2-dev libudev-dev

test-stable:
  stage: test
  image: "rust:latest"
  script:
    - cargo test

pages:
  stage: deploy
  image: "rust:latest"
  script:
    - cargo doc
    - mv target/doc public
  artifacts:
    paths:
      - public
  only:
    - master

