[package]
name = "hexworld-ggez"
version = "0.1.0"
authors = ["Roman S. Borschel <roman@pkaboo.org>"]
edition = "2018"

[dependencies]
hexworld = { path = "../core" }
ggez = "^0.4"
# ggez = { git = "https://github.com/ggez/ggez", branch="devel" }
