[package]
name = "hexkit-ggez"
version = "0.1.0"
authors = ["Roman S. Borschel <roman@pkaboo.org>"]
edition = "2018"
license = "MPL-2.0"
description = "Creating games with hexkit and ggez."

[dependencies]
hexkit = { path = "../core" }
ggez = { git = "https://github.com/ggez/ggez" }
