[package]
name = "hexworld-ggez-demo"
version = "0.1.0"
authors = ["Roman S. Borschel <roman@pkaboo.org>"]
edition = "2018"

[dependencies]
hexworld = { path = "../core" }
hexworld-ggez = { path = "../ggez" }
# ggez = "0.5.0-rc.0"
ggez = { path = "../../ggez" }
nalgebra = "^0.16"

