[package]
name = "hexworld-ggez-demo"
version = "0.1.0"
authors = ["Roman S. Borschel <roman@pkaboo.org>"]

[dependencies]
hexworld = { path = "../core" }
hexworld-ggez = { path = "../ggez" }
# ggez = { git = "https://github.com/ggez/ggez", branch="devel" }
ggez = "*"
nalgebra = "^0.14"

