[package]
name = "hexworld"
version = "0.1.0"
authors = ["Roman S. Borschel <roman@pkaboo.org>"]

[dependencies]
nalgebra = "^0.14"
num-rational = "^0.2"
num-traits = "^0.2"
num-derive = "^0.2"

[dev-dependencies]
quickcheck = "^0.6"
rand = "^0.6"
