[package]
name = "hexworld"
version = "0.1.0"
authors = ["Roman S. Borschel <roman@pkaboo.org>"]
edition = "2018"

[dependencies]
nalgebra = { version = "0.18", features = ["mint"] }
num-traits = "0.2"
num-derive = "0.3"
either = "1.5"

[dev-dependencies]
quickcheck = "0.9"
rand = "0.7"
